spring:
  profiles: default
  application:
    name: spring-cloud-config-test
server:
  port: 8080
app:
    name: loaded my local value....
    address: loaded local address.....
management:
  endpoints:
    web:
      exposure:
        include: '*'